- alias: 空气差@阳台
  trigger:
    - platform: numeric_state
      entity_id: sensor.balcony_pm25
      above: 50
      for:
        minutes: 5
    - platform: state
      entity_id: binary_sensor.door_window_sensor_158d000228a52b
      from: 'off'
      to: 'on'
      for:
        seconds: 30
  condition:
    - condition: state
      entity_id: binary_sensor.door_window_sensor_158d000228a52b
      state: 'on'
    - condition: time
      after: '06:00'
      before: '23:00'
  action:
    - service: miai.say
      data_template:
        message: '阳台PM2.5为{% set PM25 = states("sensor.balcony_pm25") | int %}{{ PM25 }}，{% if PM25 < 20 %}空气很好{% elif PM25 < 40 %}空气不错{% elif PM25 < 60 %}空气一般{% elif PM25 < 80 %}空气不好{% else %}空气污染，请关好门窗{% endif %}'

- alias: 空气好@阳台
  trigger:
    - platform: numeric_state
      entity_id: sensor.balcony_pm25
      below: 20
      for:
        minutes: 10
  condition:
    - condition: time
      after: '07:00'
      before: '22:00'
    - condition: state
      entity_id: binary_sensor.door_window_sensor_158d000228a52b
      state: 'off'
    - condition: numeric_state
      entity_id: sensor.balcony_temperature
      above: 10
      below: 30
    - condition: or
      conditions:
        - condition: numeric_state
          entity_id: sensor.aircat_pm25
          above: 20
        - condition: numeric_state
          entity_id: sensor.fresher_co2
          above: 800
  action:
    - service: miai.say
      data:
        message: 外面空气很好，可以打开门窗

- alias: 空气差@室内
  trigger:
    - platform: numeric_state
      entity_id: sensor.aircat_pm25
      above: 40
    - platform: numeric_state
      entity_id: sensor.fresher_co2
      above: 900
    - platform: numeric_state
      entity_id: sensor.fresher2_co2
      above: 1000
    - platform: numeric_state
      entity_id: sensor.aircat_hcho
      above: 0.08
  action:
    - service: light.turn_on
      data_template:
        entity_id: light.gateway_light_34ce0090901a
        color_name: '{% if states("sensor.fresher_co2") | int > 900 %}red{% elif states("sensor.fresher2_co2") | int > 1000 %}purple{% elif states("sensor.aircat_hcho") | float > 0.08 %}green{% elif states("sensor.aircat_pm25") | int > 40 %}blue{% endif %}'
        brightness: 10
    - condition: time
      after: '06:00'
      before: '23:00'
    - service: miai.say
      data_template:
        message: '{% set PM25 = states("sensor.aircat_pm25") | int %}{% if PM25 >= 40 %}PM2.5为{{ PM25 }}，空气不好。{% endif %}{% set CO2 = states("sensor.fresher_co2") | int %}{% if CO2 >= 900 %}二氧化碳浓度为{{ CO2 }}，空气很闷。{% endif %}{% set HCHO = states("sensor.aircat_hcho") | float %}{% if HCHO > 0.2 %}甲醛浓度为{{ HCHO }}，注意通风。{% endif %}'

- alias: 空气好@室内
  trigger:
    - platform: numeric_state
      entity_id: sensor.aircat_pm25
      below: 40
    - platform: numeric_state
      entity_id: sensor.fresher_co2
      below: 900
    - platform: numeric_state
      entity_id: sensor.fresher2_co2
      below: 1000
    - platform: numeric_state
      entity_id: sensor.aircat_hcho
      below: 0.08
  condition:
    - condition: numeric_state
      entity_id: sensor.aircat_pm25
      below: 40
    - condition: numeric_state
      entity_id: sensor.fresher_co2
      below: 900
    - condition: numeric_state
      entity_id: sensor.fresher2_co2
      below: 1000
    - condition: numeric_state
      entity_id: sensor.aircat_hcho
      below: 0.08
    - condition: state
      entity_id: light.gateway_light_34ce0090901a
      state: 'on'
  action:
    - service: light.turn_off
      entity_id: light.gateway_light_34ce0090901a
