- alias: 窗帘关@书房
  trigger:
    - platform: time
      at: '12:30:00'
    - platform: numeric_state
      entity_id: sensor.studyroom_lightness
      above: 180
      for:
        minutes: 10
  condition:
    - condition: numeric_state
      entity_id: sensor.studyroom_lightness
      above: 180
    - condition: time
      after: '12:00'
      before: '16:00'
  action:
    - service: cover.close_cover
      entity_id: cover.studyroom_cover

- alias: 窗帘开@书房
  trigger:
    - platform: sun
      event: sunset
      offset: '-01:30:00'
  condition:
    - condition: state
      entity_id: cover.studyroom_cover
      state: closed
    - condition: state
      entity_id: switch.projector
      state: 'off'
  action:
    - service: cover.open_cover
      entity_id: cover.studyroom_cover
