- alias: 过道灯白天开
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_sensor_158d0001d66ce9
      to: 'on'
  condition:
    - condition: state
      entity_id: sun.sun
      state: above_horizon
    - condition: numeric_state
      entity_id: sensor.illumination_34ce0090901a
      below: 300
    - condition: state
      entity_id: switch.projector
      state: 'off'
  action:
    - service: light.turn_on
      entity_id: light.passage_light
    - service: automation.turn_off
      entity_id: automation.guo_dao_deng_bai_tian_guan
    - service: automation.turn_on
      entity_id: automation.guo_dao_deng_bai_tian_guan

- alias: 过道灯白天关
  initial_state: false
  trigger:
    - platform: time_pattern
      minutes: '/5'
  condition:
    - condition: state
      entity_id: sun.sun
      state: above_horizon
    - condition: state
      entity_id: binary_sensor.motion_sensor_158d0001d66ce9
      state: 'off'
  action:
    - service: light.turn_off
      entity_id: light.passage_light
    - service: automation.turn_off
      entity_id: automation.guo_dao_deng_bai_tian_guan

- alias: 过道灯晚上开
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_sensor_158d0001d66ce9
      from: 'off'
      to: 'on'
    - platform: state
      entity_id: binary_sensor.door_window_sensor_158d0001f3e5be
      from: 'off'
      to: 'on'
  condition:
    - condition: state
      entity_id: sun.sun
      state: below_horizon
    - condition: time
      after: '18:00'
      before: '21:30'
    - condition: state
      entity_id: switch.projector
      state: 'off'
  action:
    - service: light.turn_on
      entity_id: light.passage_light

- alias: 过道灯晚上关
  trigger:
    - platform: time
      at: '21:30:00'
    - platform: state
      entity_id: binary_sensor.motion_sensor_158d0001d66ce9
      to: 'off'
  condition:
    - condition: time
      after: '21:29'
      before: '23:59'
    - condition: state
      entity_id: binary_sensor.motion_sensor_158d0001d66ce9
      state: 'off'
    - condition: state
      entity_id: binary_sensor.motion_sensor_158d0001f4a238
      state: 'off'
    - condition: state
      entity_id: media_player.x9400e
      state: 'off'
  action:
    - service: light.turn_off
      entity_id: light.passage_light

- alias: 过道背景灯感应
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_sensor_158d0001d66ce9
      from: 'off'
      to: 'on'
  condition:
    - condition: time
      after: '21:30'
      before: '06:00'
    - condition: state
      entity_id: light.passage_light
      state: 'off'
  action:
    - service: light.turn_on
      data:
        entity_id: light.gateway_light_34ce0090901a
        color_name: white
        brightness: 100
    - wait_template: '{{ is_state("binary_sensor.motion_sensor_158d0001d66ce9", "off") }}'
    - service: light.turn_off
      entity_id: light.gateway_light_34ce0090901a
