- alias: 调节净化器@餐厅
  trigger:
    - platform: state
      entity_id: sensor.aircat_pm25
  action:
    - service: actuator.actuate
      data:
        sensor_id: sensor.aircat_pm25
        sensor_values: [10, 20, 50]
        entity_id: fan.purifier5
        entity_attr: speed
        entity_values: [low, medium, high]

- alias: 调节净化器@主卧
  trigger:
    - platform: state
      entity_id: sensor.fresher2_pm25
  action:
    - service: actuator.actuate
      data:
        sensor_id: sensor.fresher2_pm25
        sensor_values: [7, 15, 40]
        alt_sensor_values: [5, 20, 40]
        entity_id: fan.purifier6
        entity_attr: speed
        entity_values: [low, medium, high]

- alias: 调节净化器@次卧
  trigger:
    - platform: state
      entity_id: sensor.purifier_pm25
  action:
    - service: actuator.actuate
      data:
        sensor_id: sensor.purifier_pm25
        sensor_values: [15, 40]
        alt_sensor_values: [20, 50]
        entity_id: fan.purifier
        entity_attr: speed
        entity_values: [Auto, Favorite]
        delay: 300
    - service: actuator.actuate
      data:
        sensor_id: sensor.purifier_pm25
        sensor_values: [15, 40, 60, 80]
        alt_sensor_values: [20, 50, 80, 100]
        entity_id: fan.purifier
        entity_attr: favorite_level
        service: xiaomi_miio_set_favorite_level
        service_attr: level
        entity_values: [3, 6, 9, 10]
        delay: 300

- alias: 调节净化器@儿童房
  trigger:
    - platform: state
      entity_id: sensor.purifier7_pm25
  action:
    - service: actuator.actuate
      data:
        sensor_id: sensor.purifier7_pm25
        sensor_values: [10, 20, 50]
        alt_sensor_values: [7, 30, 50]
        entity_id: fan.purifier7
        entity_attr: speed
        entity_values: [low, medium, high]

- alias: 调节净化器@书房
  initial_state: false
  trigger:
    - platform: state
      entity_id: sensor.aircat2_pm25
  action:
    - service: actuator.actuate
      data:
        sensor_id: sensor.aircat2_pm25
        sensor_values: [10, 20, 50]
        alt_sensor_values: [10, 30, 50]
        entity_id: fan.purifier4
        entity_attr: speed
        entity_values: [low, medium, high]
