- alias: 同步餐厅灯
  trigger:
    - platform: state
      entity_id: light.diningroom_light2, light.diningroom_light
  action:
    - service_template: '{% if trigger.to_state.state == "on" %}light.turn_on{% else %}light.turn_off{% endif %}'
      data_template:
        entity_id: '{% if trigger.entity_id == "light.diningroom_light2" %}light.diningroom_light{% else %}light.diningroom_light2{% endif %}'

- alias: 同步客厅灯
  trigger:
    - platform: state
      entity_id: light.livingroom_light2, light.livingroom_light
  action:
    - service_template: '{% if trigger.to_state.state == "on" %}light.turn_on{% else %}light.turn_off{% endif %}'
      data_template:
        entity_id: '{% if trigger.entity_id == "light.livingroom_light2" %}light.livingroom_light{% else %}light.livingroom_light2{% endif %}'

- alias: 同步过道灯
  trigger:
    - platform: state
      entity_id: light.passage_light2, light.passage_light
  action:
    - service_template: '{% if trigger.to_state.state == "on" %}light.turn_on{% else %}light.turn_off{% endif %}'
      data_template:
        entity_id: '{% if trigger.entity_id == "light.passage_light2" %}light.passage_light{% else %}light.passage_light2{% endif %}'

- alias: 同步书房灯
  trigger:
    - platform: state
      entity_id: light.studyroom_light2, light.studyroom_light3, light.studyroom_light
  action:
    - service_template: '{% if trigger.to_state.state == "on" %}light.turn_on{% else %}light.turn_off{% endif %}'
      data_template:
        entity_id: '{% if trigger.entity_id == "light.studyroom_light2" %}light.studyroom_light,light.studyroom_light3{% elif trigger.entity_id == "light.studyroom_light3" %}light.studyroom_light,light.studyroom_light2{% else %}light.studyroom_light2,light.studyroom_light3{% endif %}'
