- alias: 调节空调@主卧
  trigger:
    - platform: time
      at: '20:30:01'
    - platform: state
      entity_id: sensor.fresher2_temperature
  condition:
    - condition: time
      after: '20:00'
      before: '07:20'
  action:
    - service: actuator.actuate
      data:
        sensor_id: sensor.fresher2_temperature
        sensor_values: [27.5, 29.3, 30, 31, 32]
        alt_sensor_values: [28, 29.5, 30, 31, 32]
        #alt_sensor_values: [28.5, 29.5, 30, 31, 32]
        alt_time_range: [2, 7]
        entity_id: climate.daikin3
        entity_attr: fan_mode
        entity_values: [一档, 二档, 三档, 四档, 五档]

- alias: 调节空调@儿童房
  trigger:
    - platform: time
      at: '20:00:01'
    - platform: state
      entity_id: sensor.purifier7_temperature
  condition:
    - condition: time
      after: '20:00'
      before: '07:20'
  action:
    - service: actuator.actuate
      data:
        sensor_id: sensor.purifier7_temperature
        sensor_values: [22, 22.5, 23, 24, 25]
        alt_sensor_values: [23.2, 24, 25, 26, 27]
        alt_time_range: [2, 8]
        entity_id: climate.daikin4
        entity_attr: fan_mode
        entity_values: [一档, 二档, 三档, 四档, 五档]
        delay: 0

- alias: 调节空调@书房
  trigger:
    - platform: time
      at: '20:30:01'
    - platform: state
      entity_id: sensor.purifier4_temperature
  condition:
    - condition: time
      after: '20:30'
      before: '07:20'
  action:
    - service: actuator.actuate
      data:
        sensor_id: sensor.purifier4_temperature
        #sensor_values: [28, 28.5, 32, 34] #fan_temperature
        #alt_sensor_values: [28.8, 30, 32, 34]
        sensor_values: [29.5, 30, 32, 33]
        alt_sensor_values: [30, 31, 32, 33]
        alt_time_range: [2, 8]
        entity_id: climate.mitsubishi
        entity_attr: fan_mode
        entity_values: [low, mid, high, highest]
        delay: 0

- alias: 调节风扇@书房
  trigger:
    - platform: time
      at: '20:30:01'
    - platform: state
      entity_id: sensor.purifier4_temperature
  condition:
    - condition: time
      after: '20:30'
      before: '07:20'
  action:
    - service: actuator.actuate
      data:
        sensor_id: sensor.purifier4_temperature
        #sensor_values: [24, 27.5, 30, 32] #fan_temperature
        #alt_sensor_values: [25, 28.5, 32, 34]
        sensor_values: [26, 28.5, 32, 33]
        alt_sensor_values: [27, 30, 32, 34]
        alt_time_range: [2, 7]
        entity_id: fan.fan2
        entity_attr: speed_level
        #service: set_speed
        service_attr: speed
        entity_values: [Level 1, Level 2, Level 3, Level 4]
        delay: 0

- alias: 调节风扇@儿童房
  trigger:
    - platform: time
      at: '20:00:01'
    - platform: state
      entity_id: sensor.purifier7_temperature
  condition:
    - condition: time
      after: '20:00'
      before: '07:20'
  action:
    - service: actuator.actuate
      data:
        sensor_id: sensor.purifier7_temperature
        sensor_values: [20, 22, 24, 25]
        alt_sensor_values: [21, 23, 25, 26]
        alt_time_range: [2, 7]
        entity_id: fan.fan
        entity_attr: speed_level
        #service: set_speed
        service_attr: speed
        entity_values: [Level 1, Level 2, Level 3, Level 4]
        delay: 0
