- alias: 洗手间灯感应开
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_sensor_158d0001f4a238
      to: 'on'
  condition:
    # - condition: state
    #   entity_id: light.washroom_light
    #   state: 'off'
    - condition: state
      entity_id: sun.sun
      state: below_horizon
  action:
    - service: light.turn_on
      entity_id: light.washroom_light
    - service: automation.turn_off
      entity_id: automation.xi_shou_jian_deng_yan_chi_guan
    - service: automation.turn_on
      entity_id: automation.xi_shou_jian_deng_yan_chi_guan

- alias: 洗手间灯延迟关
  initial_state: false
  trigger:
    - platform: time_pattern
      minutes: '/3'
  condition:
    - condition: state
      entity_id: binary_sensor.motion_sensor_158d0001f4a238
      state: 'off'
  action:
    - service: light.turn_off
      entity_id: light.washroom_light
    - service: automation.turn_off
      entity_id: automation.xi_shou_jian_deng_yan_chi_guan
